debuggin

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -55,11 +55,27 @@ virtualenv() {
     python "$buildpack/vendor/virtualenv-1.11.6/virtualenv.py" "$@"
 }
 
-name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
-ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
+if test -f $build/Godeps
+then
+    name=$(<$build/Godeps jq -r .ImportPath)
+    ver=$(<$build/Godeps jq -r .GoVersion)
+elif test -d $build/Godeps
+then
+    name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
+    ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
+else
+#elif test -f $build/.godir
+#then
+    name=$(cat $build/.godir)
+    ver=go${GOVERSION:-1.3}
+#else
+#    echo >&2 " !     A .godir is required. For instructions:"
+#    echo >&2 " !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku"
+#    exit 1
+fi
 
-#file=${GOFILE:-$ver.$(uname|tr A-Z a-z)-amd64$(platext $ver).tar.gz}
-#url=${GOURL:-$(urlfor $ver $file)}
+file=${GOFILE:-$ver.$(uname|tr A-Z a-z)-amd64$(platext $ver).tar.gz}
+url=${GOURL:-$(urlfor $ver $file)}
 
 if test -e $build/bin && ! test -d $build/bin
 then
